version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'student-attendance'
      MYSQL_USER: 'medi'
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql # Mounts a volume to persist database data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - '8080:8080' # Adjust according to your application's requirements
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/student-attendance?autoReconnect=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    privileged: true
    depends_on:
      - db
    devices:
      - "/dev/ttyUSB2"

# Define the volume here
volumes:
  db_data:
    driver: local
