services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-grafana-network
  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - prometheus-grafana-network



  db:
    image: mysql:latest
    container_name: db_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'student-attendance'
      MYSQL_USER: 'medi'
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/student-attendance?autoReconnect=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    privileged: true
    depends_on:
      - db
    devices:
      - "/dev/ttyUSB2"

volumes:
  db_data:
    driver: local

networks:
  prometheus-grafana-network:


